libusbgx: Fix doc build with new doxygen version
Doc build may fail with newest doxygen with error:
error: the type 'dirs' is not supported for the entry tag within a navindex! Check your layout file!

Fix this by simply remove the line that caused the error.

Signed-off-by: Krzysztof Opasiak <k.opasiak@samsung.com>